### ISSUE TITLE
内核版本对BTF支持问题

### ISSUE THREAD

**Issue by hz-kelpie** [ehids/ehids-agent#1]
咨询一下，对于不支持或未开启的BTF的主机有做支持吗?

**Comment by SenberHu** [comment]
ehids项目目前没有计划支持，您可以fork后修改读取内核字段方式为probe_read，同时修改makefile，下载对应系统内核kernel-header-dev包，进行编译即可。

**Comment by hz-kelpie** [comment]
明白了 对主机有要求

**Comment by SenberHu** [comment]
是的 不支持CORE的机器，只能分别适配，和内核热补丁适配方式相同。开发中还有问题的话，欢迎+v ：senberhu沟通
