### ISSUE TITLE
couldn't init manager: error:program trace_ret_udp_recvmsg: load program: invalid argument: R1 type=ctx expected=fp

### ISSUE THREAD

**Issue by heatice** [ehids/ehids-agent#10]
couldn't init manager: error:program trace_ret_udp_recvmsg: load program: invalid argument: R1 type=ctx expected=fp；

![图片](https://user-images.githubusercontent.com/52515695/196330320-82c5551c-b179-4212-9bdd-3f4d308222f0.png)

![图片](https://user-images.githubusercontent.com/52515695/196330670-d42c8328-0d10-4b47-9657-59b3f70063ab.png)

无效的参数 初始化  trace_ret_udp_recvmsg 函数的时候

系统 ubuntu22.04 内核版本 5.15.0-50-generic

**Comment by cfc4n** [comment]
没有精力维护这个项目，建议尝试其他云原生的运行时安全防御软件，也都是基于eBPF实现的。

1. https://github.com/falcosecurity/falco  
2. https://github.com/aquasecurity/tracee 
3. https://github.com/cilium/tetragon
