### ISSUE TITLE
程序无法在arm64架构上无法正确运行

### ISSUE THREAD

**Issue by perlh** [ehids/ehids-agent#12]
编译好的程序在ARM 的linux系统上无法运行？
请问能分享关于这个项目的微信群吗？感谢

# system：
orangepi-r1plus-lts:~:% uname -a
Linux orangepi-r1plus-lts 5.15.76-rockchip64 #22.08.8 SMP PREEMPT Sun Oct 30 10:57:32 CET 2022 aarch64 GNU/Linux

检查发现系统好像支持ebpf
orangepi-r1plus-lts:~:% llc  --version
LLVM (http://llvm.org/):
  LLVM version 11.0.1
  
  Optimized build.
  Default target: aarch64-unknown-linux-gnu
  Host CPU: cortex-a53

  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_32 - AArch64 (little endian ILP32)
    aarch64_be - AArch64 (big endian)
    amdgcn     - AMD GCN GPUs
    arm        - ARM
    arm64      - ARM64 (little endian)
    arm64_32   - ARM64 (little endian ILP32)
    armeb      - ARM (big endian)
    avr        - Atmel AVR Microcontroller
    bpf        - BPF (host endian)
    bpfeb      - BPF (big endian)
    bpfel      - BPF (little endian)
    hexagon    - Hexagon
    ...

# error：
报错如下：
orangepi-r1plus-lts:~:% sudo ./ehids-agent   
2022/11/23 18:13:10 process pid: 6089
2022/11/23 18:13:10 start to run EBPFProbeUJavaRASP module
2022/11/23 18:13:10 start to run EBPFProbeBPFCall module
2022/11/23 18:13:10 start to run EBPFProbeKTCP module
2022/11/23 18:13:10 start to run EBPFProbeKTCPSec module
2022/11/23 18:13:10 start to run EBPFProbeKUDP module
2022/11/23 18:13:10 start to run EBPFProbeProc module
2022/11/23 18:13:10 start to run EBPFProbeUDNS module
2022/11/23 18:13:10 couldn't init manager: error:program java_JDK_execvpe: CO-RE relocations: no BTF found for kernel version 5.15.76-rockchip64: not supported , couldn't load eBPF programs, cs:&{map[jdk_execvpe_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0)] map[java_JDK_execvpe:0x400006ac80] LittleEndian}
2022/11/23 18:13:10 couldn't init manager: error:program getaddrinfo_entry: CO-RE relocations: no BTF found for kernel version 5.15.76-rockchip64: not supported , couldn't load eBPF programs, cs:&{map[currres:Hash(keySize=4, valueSize=8, maxEntries=1024, flags=0) events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0) start:Hash(keySize=4, valueSize=84, maxEntries=1024, flags=0)] map[getaddrinfo_entry:0x4000284460 getaddrinfo_return:0x4000284500] LittleEndian}
2022/11/23 18:13:10 couldn't init manager: error:program kprobe__security_socket_connect: CO-RE relocations: no BTF found for kernel version 5.15.76-rockchip64: not supported , couldn't load eBPF programs, cs:&{map[ipv4_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0) ipv6_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0) other_socket_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0)] map[kprobe__security_socket_connect:0x400006b0e0] LittleEndian}
2022/11/23 18:13:10 couldn't init manager: error:program kprobe__tcp_set_state: CO-RE relocations: no BTF found for kernel version 5.15.76-rockchip64: not supported , couldn't load eBPF programs, cs:&{map[conns:Hash(keySize=8, valueSize=40, maxEntries=10240, flags=0) events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0)] map[kprobe__tcp_set_state:0x400026a960] LittleEndian}
2022/11/23 18:13:10 couldn't init manager: error:program trace_ret_udp_recvmsg: CO-RE relocations: no BTF found for kernel version 5.15.76-rockchip64: not supported , couldn't load eBPF programs, cs:&{map[dns_data:PerCPUArray(keySize=4, valueSize=532, maxEntries=1, flags=0) dns_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0) tbl_udp_msg_hdr:Hash(keySize=8, valueSize=8, maxEntries=10240, flags=0)] map[trace_ret_udp_recvmsg:0x400006b400 trace_udp_recvmsg:0x400006b360] LittleEndian}
2022/11/23 18:13:10 couldn't init manager: error:program tracepoint_sys_enter_bpf: CO-RE relocations: no BTF found for kernel version 5.15.76-rockchip64: not supported , couldn't load eBPF programs, cs:&{map[bpf_context:LRUHash(keySize=8, valueSize=424, maxEntries=2048, flags=0) bpf_context_gen:Array(keySize=4, valueSize=424, maxEntries=1, flags=0) bufs:PerCPUArray(keySize=4, valueSize=4096, maxEntries=3, flags=0) events:PerfEventArray(keySize=0, valueSize=0, maxEntries=4, flags=0)] map[tracepoint_sys_enter_bpf:0x40002852c0] LittleEndian}
2022/11/23 18:13:10 couldn't init manager: error:program kretprobe_copy_process: CO-RE relocations: no BTF found for kernel version 5.15.76-rockchip64: not supported , couldn't load eBPF programs, cs:&{map[ringbuf_proc:RingBuf(keySize=0, valueSize=0, maxEntries=16777216, flags=0)] map[kretprobe_copy_process:0x4000285ea0] LittleEndian}

**Comment by cfc4n** [comment]
精力有限，无法支持对该项目的迭代。  并且，用eBPF技术实现的agent特别多，特别卷，可以尝试一下tetragon\tracee\falco等产品。

不过，你也可以自己修复这个错误，参考 https://github.com/ehids/ecapture 的 代码。

**Comment by cfc4n** [comment]
微信群满了，很难管理。 推荐QQ群。  可以在「榫卯江湖」微信公众号里的菜单里找到QQ群二维码。
