### ISSUE TITLE
针对JDK_execvpe第三个参数argv的提取问题

### ISSUE THREAD

**Issue by hututu2** [ehids/ehids-agent#17]
大佬可以指导一下如何获取到argv吗，对于指针数组char *argv[]的获取有点没有头绪。我尝试使用下面的代码，但拿到的字符串是空的：
    const char **argv = (const char **)PT_REGS_PARM3(ctx);
    if (!argv) {
        return 0;
    }
    const char *arg_p= NULL;
    bpf_probe_read_user(&arg_p,sizeof(arg_p),&argv[0]);
    bpf_probe_read_user_str(val.argv, sizeof(val.argv),arg_p);   
结构体的定义如下：
struct jdk_execvpe {
    u32 pid;
    u64 mode;
    char file[128];
    char argv[128];
} __attribute__((packed));

**Comment by cfc4n** [comment]
嗯？怎么关了呢？

**Comment by hututu2** [comment]
问题已经解决啦。这样分两步去读取没问题，是我用户态代码Decode里面没有把它的读取部分加进去：
	if err = binary.Read(buf, binary.LittleEndian, &e.Argv); err !=nil{
		return
	}
