### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by fwxiong** [ehids/ehids-agent#2]
2022/03/25 14:21:54 https://github.com/ehids/ehids-agent
2022/03/25 14:21:54 process pid: 212631
2022/03/25 14:21:54 start to run EBPFProbeProc module
2022/03/25 14:21:54 start to run EBPFProbeUDNS module
2022/03/25 14:21:54 start to run EBPFProbeUJavaRASP module
2022/03/25 14:21:54 start to run EBPFProbeBPFCall module
2022/03/25 14:21:54 start to run EBPFProbeKTCP module
2022/03/25 14:21:54 start to run EBPFProbeKTCPSec module
2022/03/25 14:21:54 start to run EBPFProbeKUDP module
2022/03/25 14:21:54 couldn't init manager: error:map ringbuf_proc: map create without BTF: invalid argument , couldn't load eBPF programs, cs:&{map[ringbuf_proc:RingBuf(keySize=0, valueSize=0, maxEntries=16777216, flags=0)] map[kretprobe_copy_process:0xc000165220] LittleEndian}

Linux VM-16-8-ubuntu 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
root@VM-16-8-ubuntu:/home/tools/ehids-agent# cat /etc/issue
Ubuntu 20.04 LTS \n \l

**Comment by cfc4n** [comment]
应该是内核版本太低了，不支持BPF_MAP_TYPE_RINGBUF类型的MAP，换高一点版本，比如5.12以上。
