### ISSUE TITLE
Linux ubuntu 5.13.0-39-generic 运行报错不支持 ringbuf_proc

### ISSUE THREAD

**Issue by xlango** [ehids/ehids-agent#4]
报错：
       couldn't init manager: error:program kretprobe_copy_process: CO-RE relocations: relocate unnamed or anonymous type struct#170[""]: not supported , couldn't load eBPF programs, cs:&{map[ringbuf_proc:RingBuf(keySize=0, valueSize=0, maxEntries=16777216, flags=0)] map[kretprobe_copy_process:0xc0001c00a0] LittleEndian}

内核版本：
Linux ubuntu 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cfc4n** [comment]
clang之类版本信息有吗？

**Comment by xlango** [comment]
clang version 10.0.0-4ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by cfc4n** [comment]
5.13内核是 20.04 吗？ 明天我装个系统测测。

**Comment by xlango** [comment]
Ubuntu 20.04 LTS

**Comment by cfc4n** [comment]
修复这个问题了， 试试最新版。 https://github.com/ehids/ehids-agent/commit/0d50e7f3ab5d55bf19f97d6b8855de3d4c615b25

**Comment by cfc4n** [comment]
我测试了，确认问题修复，关issue了。如果你测试有问题，再重新打开。

**Comment by xlango** [comment]
couldn't init manager: error:program kretprobe_copy_process: CO-RE relocations: relocate unnamed or anonymous type struct#167[""]: not supported , couldn't load eBPF programs, cs:&{map[ringbuf_proc:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0)] map[kretprobe_copy_process:0xc00010aaa0] LittleEndian}
