### ISSUE TITLE
kprobe security_socket_connect 拿不到 本地ip、port端口信息

### ISSUE THREAD

**Issue by rockingl** [ehids/ehids-agent#6]
hi，陈大佬！
kprobe security_socket_connect挂载拿不到正确的，五元组信息。
能帮忙看下么？

<img width="979" alt="image" src="https://user-images.githubusercontent.com/20380742/169796422-db85cf43-3f2d-45ed-97b6-40365b697adf.png">

**Comment by cfc4n** [comment]
不是issue，三两句说不清。  公众号里留信息，我拉你进群。

**Comment by rockingl** [comment]
好的 关注公众号 + 并留了消息了

**Comment by cfc4n** [comment]
> 好的 关注公众号 + 并留了消息了
没收到你发的信息。。

**Comment by cfc4n** [comment]
https://github.com/ehids/ecapture/blob/master/images/wechat_gzhh.png  这个。
