### ISSUE TITLE
获取到的 dport 一直是 0 ？

### ISSUE THREAD

**Issue by MetaT1an** [ehids/ehids-agent#7]
https://github.com/ehids/ehids-agent/blob/b67d1bed310195e4c6a03015ffe442a4d7c03a02/kern/udp_lookup_kern.c#L49

按上述写法，获取到的 dport 一直都是 0，这是为什么呀？

**Comment by cfc4n** [comment]
还是要补充你的环境信息，系统版本、编译器版本、内核版本等。 也可以加群讨论，【榫卯江湖】公众包里留言“微信群”，会发送二维码给你。
